"""Perceptual hashing: decoding, invariance, budget and cache behaviour.

The fixtures in `tests/fixtures/media/` are generated, not scraped — but they
are generated by *real encoders* (`sips`, i.e. Apple ImageIO, and ImageMagick),
which is the part that matters. A hand-rolled JPEG would only prove the decoder
agrees with itself. See that directory's README for the exact commands.
"""

from __future__ import annotations

import asyncio
import struct
import zlib
from datetime import datetime
from pathlib import Path

import numpy as np
import pytest

from botsensai.config import get_settings
from botsensai.media.hasher import MediaHasher, thumbnail_url
from botsensai.media.imagecodec import UnsupportedImage, decode_luma, sniff_format
from botsensai.media.phash import (
    cluster_by_distance,
    exact_label,
    hamming_distance,
    perceptual_hash,
    perceptual_label,
    perceptual_values,
    resample,
)
from botsensai.models import Platform, SocialPost

FIXTURES = Path(__file__).parent / "fixtures" / "media"


def _load(name: str) -> np.ndarray:
    return decode_luma((FIXTURES / name).read_bytes())


def _hash(name: str) -> str:
    return perceptual_hash(_load(name))


def _png_bytes(array: np.ndarray, *, filters: tuple[int, ...] = (0,)) -> bytes:
    """Minimal 8-bit RGB PNG encoder, so tests can synthesize images.

    `filters` cycles the scanline filter type, which is the only way to reach
    the decoder's Sub/Up/Average/Paeth paths deliberately — a real encoder picks
    them adaptively and may never emit the one that is broken.
    """
    height, width, _ = array.shape
    bpp = 3
    lines: list[bytes] = []
    prior = bytearray(width * bpp)
    for row in range(height):
        ftype = filters[row % len(filters)]
        line = bytearray(array[row].tobytes())
        lines.append(bytes([ftype]) + _apply_png_filter(line, prior, ftype, bpp))
        prior = line

    def chunk(name: bytes, body: bytes) -> bytes:
        payload = name + body
        return struct.pack(">I", len(body)) + payload + struct.pack(">I", zlib.crc32(payload))

    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(b"".join(lines), 6))
        + chunk(b"IEND", b"")
    )


def _apply_png_filter(line: bytearray, prior: bytearray, ftype: int, bpp: int) -> bytes:
    """The forward direction of RFC 2083's five filters."""
    out = bytearray(len(line))
    for i in range(len(line)):
        left = line[i - bpp] if i >= bpp else 0
        upleft = prior[i - bpp] if i >= bpp else 0
        predictor = {
            0: 0,
            1: left,
            2: prior[i],
            3: (left + prior[i]) >> 1,
            4: _paeth_predictor(left, prior[i], upleft),
        }[ftype]
        out[i] = (line[i] - predictor) & 0xFF
    return bytes(out)


def _paeth_predictor(a: int, b: int, c: int) -> int:
    p = a + b - c
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    return b if pb <= pc else c


def _pattern(size: int, phase: float = 0.0) -> np.ndarray:
    grid_y, grid_x = np.mgrid[0:size, 0:size].astype(float)
    values = 128 + 100 * np.sin(grid_x / (size / 12.0) + phase) * np.cos(grid_y / (size / 9.0))
    return np.dstack([values, values, values]).clip(0, 255).astype(np.uint8)


# --------------------------------------------------------------------------- #
# The acceptance criterion
# --------------------------------------------------------------------------- #


def test_resized_and_reencoded_copy_hashes_close():
    """256px lossless PNG vs a 96px JPEG at quality 35 — same picture, ~1/7 the pixels."""
    distance = hamming_distance(_hash("alpha.png"), _hash("alpha_small.jpg"))
    assert distance is not None and distance <= 6, distance


def test_unrelated_image_is_not_close():
    distance = hamming_distance(_hash("alpha.png"), _hash("beta.png"))
    assert distance is not None and distance > 6, distance
    # Independent 64-bit hashes sit near 32; anything much below that would mean
    # the hash is collapsing distinct pictures together.
    assert distance >= 20, distance


# --------------------------------------------------------------------------- #
# Decoding
# --------------------------------------------------------------------------- #


def test_png_and_jpeg_of_the_same_picture_agree():
    """The DC-only JPEG path must land where the full PNG decode lands."""
    assert hamming_distance(_hash("alpha.png"), _hash("alpha_full.jpg")) == 0
    assert hamming_distance(_hash("beta.png"), _hash("beta.jpg")) == 0


@pytest.mark.parametrize(
    "name",
    ["alpha_restart.jpg", "alpha_gray.jpg", "alpha_444.jpg", "alpha_progressive.jpg"],
)
def test_jpeg_encoder_options_do_not_move_the_hash(name):
    """Restart intervals, greyscale, 4:4:4 chroma and progressive are all in the wild."""
    assert hamming_distance(_hash("alpha.png"), _hash(name)) == 0


def test_progressive_jpeg_is_decoded_not_refused():
    """Measured 2026-08-04: every image pbs.twimg.com served was progressive.

    A decoder that refuses them produces exactly zero coverage on X, which is
    the surface most of the social family depends on.
    """
    decoded = _load("alpha_progressive.jpg")
    assert decoded.shape == (32, 32)
    assert np.abs(decoded - resample(_load("alpha.png"), 32)).mean() < 4.0


def test_progressive_jpeg_without_a_leading_dc_scan_is_refused():
    """Reordered scans would need the AC passes this decoder exists to skip."""
    data = bytearray((FIXTURES / "alpha_progressive.jpg").read_bytes())
    marker = data.index(b"\xff\xda")
    length = int.from_bytes(data[marker + 2 : marker + 4], "big")
    # Ss lives after the per-component table bytes; move the scan off DC.
    data[marker + 2 + length - 3] = 1
    with pytest.raises(UnsupportedImage, match="leading DC scan"):
        decode_luma(bytes(data))


def test_arithmetic_and_lossless_frames_are_refused():
    data = bytearray((FIXTURES / "alpha_full.jpg").read_bytes())
    data[data.index(b"\xff\xc0") + 1] = 0xC9  # SOF9, arithmetic coding
    with pytest.raises(UnsupportedImage, match="unsupported jpeg frame"):
        decode_luma(bytes(data))


def test_jpeg_shape_is_one_eighth_scale():
    """DC-only decoding yields one sample per 8x8 block, by construction."""
    assert _load("alpha_full.jpg").shape == (32, 32)
    assert _load("alpha.png").shape == (256, 256)


def test_sniff_reads_magic_bytes_not_content_type():
    assert sniff_format((FIXTURES / "alpha.png").read_bytes()) == "png"
    assert sniff_format((FIXTURES / "alpha_full.jpg").read_bytes()) == "jpeg"
    assert sniff_format(b"GIF89a....") == "gif"
    assert sniff_format(b"RIFF\x00\x00\x00\x00WEBPVP8 ") == "webp"
    assert sniff_format(b"<html>") == "unknown"


@pytest.mark.parametrize(
    "payload",
    [b"", b"<html>not an image</html>", b"\x89PNG\r\n\x1a\n" + b"\x00" * 40],
)
def test_undecodable_payloads_raise(payload):
    with pytest.raises(UnsupportedImage):
        decode_luma(payload)


def test_truncated_jpeg_raises_rather_than_hashing_a_fragment():
    data = (FIXTURES / "alpha_full.jpg").read_bytes()
    with pytest.raises(UnsupportedImage):
        decode_luma(data[: len(data) // 2])


def test_pixel_budget_refuses_before_decoding():
    with pytest.raises(UnsupportedImage, match="pixel budget"):
        decode_luma((FIXTURES / "alpha.png").read_bytes(), max_pixels=1000)
    with pytest.raises(UnsupportedImage, match="pixel budget"):
        decode_luma((FIXTURES / "alpha_full.jpg").read_bytes(), max_pixels=1000)


@pytest.mark.parametrize("ftype", [0, 1, 2, 3, 4])
def test_every_png_scanline_filter_round_trips(ftype):
    """All five filters, each one used for every row, decoded exactly.

    Real encoders choose adaptively, so a fixture can leave a filter — Average
    in practice — never exercised while the file still decodes perfectly.
    """
    array = _pattern(48)
    decoded = decode_luma(_png_bytes(array, filters=(ftype,)))
    expected = array.astype(np.float64) @ np.array([0.299, 0.587, 0.114])
    assert np.abs(decoded - expected).max() < 1e-4


def test_png_with_mixed_filters_round_trips():
    array = _pattern(48)
    decoded = decode_luma(_png_bytes(array, filters=(0, 1, 2, 3, 4)))
    expected = array.astype(np.float64) @ np.array([0.299, 0.587, 0.114])
    assert np.abs(decoded - expected).max() < 1e-4


@pytest.mark.parametrize(
    ("name", "tolerance"),
    [
        ("alpha_filtered.png", 0.001),  # adaptive Sub/Up/Paeth filtering
        ("alpha_16bit.png", 0.001),  # 16-bit channels, high byte taken
        ("alpha_grayscale.png", 2.0),  # colour type 0
        ("alpha_palette.png", 3.0),  # colour type 3, quantised to 64 colours
    ],
)
def test_png_colour_types_and_depths_agree(name, tolerance):
    """Same hash *and* the same numbers.

    The hash is blind to any global scaling of the luma plane, so a hash-only
    assertion would let a channel-slicing bug through — misreading 16-bit RGB as
    8-bit yields 0.89R + 0.11G, which is a different picture that happens to
    hash the same.
    """
    assert hamming_distance(_hash("alpha.png"), _hash(name)) == 0
    assert np.abs(_load(name) - _load("alpha.png")).mean() < tolerance


@pytest.mark.parametrize("name", ["alpha_full.jpg", "alpha_restart.jpg"])
def test_jpeg_luma_matches_the_png_it_was_encoded_from(name):
    """The DC quantisation factor and the +128 level shift, pinned numerically.

    `alpha_restart.jpg` carries a luma quantisation of 10 against
    `alpha_full.jpg`'s 1, so only the pair together can tell a decoder that
    applies the quantisation table from one that ignores it.
    """
    reference = resample(_load("alpha.png"), 32)
    decoded = _load(name)
    assert decoded.shape == reference.shape
    assert np.abs(decoded - reference).mean() < 4.0
    assert abs(float(decoded.mean()) - float(reference.mean())) < 2.0


# --------------------------------------------------------------------------- #
# Hash properties
# --------------------------------------------------------------------------- #


def test_hash_is_sixteen_hex_characters():
    digest = _hash("alpha.png")
    assert len(digest) == 16
    int(digest, 16)


def test_hash_survives_area_downscaling():
    """Invariance to resampling is what makes thumbnail fetching legitimate."""
    large = decode_luma(_png_bytes(_pattern(256)))
    small = resample(large, 64)
    assert hamming_distance(perceptual_hash(large), perceptual_hash(small)) == 0


def test_hash_ignores_brightness_and_contrast():
    """The median threshold is what buys this; without it, exposure moves bits."""
    base = decode_luma(_png_bytes(_pattern(128))).astype(np.float64)
    dimmed = base * 0.55 + 20.0
    assert hamming_distance(perceptual_hash(base), perceptual_hash(dimmed)) == 0


def test_hamming_distance_refuses_incomparable_digests():
    assert hamming_distance("ab", "abcd") is None
    assert hamming_distance("zz", "00") is None


def test_perceptual_values_excludes_exact_hashes():
    mixed = [perceptual_label("00ff00ff00ff00ff"), exact_label("Mx4k4ymW"), "", "bare"]
    assert perceptual_values(mixed) == ["00ff00ff00ff00ff"]


def test_cluster_by_distance_is_single_linkage():
    """A drifts to B drifts to C: one lineage even though A and C are far apart."""
    a = 0
    b = 0b111111 << 20
    c = 0b111111_111111 << 20
    chain = [f"{v:016x}" for v in (a, b, c)]
    assert hamming_distance(chain[0], chain[2]) == 12
    assert len(set(cluster_by_distance(chain, 6))) == 1
    assert len(set(cluster_by_distance(chain, 5))) == 3


def test_cluster_labels_are_dense_and_ordered():
    hashes = [_hash("alpha.png"), _hash("beta.png"), _hash("alpha_small.jpg")]
    assert cluster_by_distance(hashes, 6) == [0, 1, 0]


# --------------------------------------------------------------------------- #
# MediaHasher: budget, cache and wiring
# --------------------------------------------------------------------------- #


def _post(*urls: str, hashes: list[str] | None = None) -> SocialPost:
    return SocialPost(
        platform=Platform.X,
        post_id="1",
        author="someone",
        as_of=datetime.fromisoformat("2026-08-01T00:00:00+00:00"),
        media_urls=list(urls),
        media_hashes=list(hashes or []),
    )


class _Fetcher:
    """Records calls and replays fixture bytes or raises."""

    def __init__(self, responses: dict[str, object]) -> None:
        self.responses = responses
        self.calls: list[str] = []

    async def __call__(self, url: str) -> bytes:
        self.calls.append(url)
        payload = self.responses.get(url, b"not an image")
        if isinstance(payload, Exception):
            raise payload
        assert isinstance(payload, bytes)
        return payload


def _hasher(responses: dict[str, object], **overrides) -> tuple[MediaHasher, _Fetcher]:
    settings = get_settings().model_copy(deep=True)
    settings.media_hash = settings.media_hash.model_copy(
        update={"prefer_thumbnails": False, **overrides}
    )
    fetcher = _Fetcher(responses)
    return MediaHasher(settings, fetcher=fetcher), fetcher


async def test_hash_posts_populates_prefixed_hashes():
    alpha = (FIXTURES / "alpha.png").read_bytes()
    hasher, fetcher = _hasher({"https://img/a.png": alpha})
    post = _post("https://img/a.png")

    assert await hasher.hash_posts([post]) == 1
    assert post.media_hashes == [perceptual_label(perceptual_hash(decode_luma(alpha)))]
    assert fetcher.calls == ["https://img/a.png"]


async def test_repeat_urls_are_served_from_cache():
    """The same meme is posted many times per sweep; it is fetched once."""
    hasher, fetcher = _hasher({"https://img/a.png": (FIXTURES / "alpha.png").read_bytes()})
    posts = [_post("https://img/a.png") for _ in range(4)]

    await hasher.hash_posts(posts)
    assert fetcher.calls == ["https://img/a.png"]
    assert all(p.media_hashes for p in posts)
    assert hasher.stats["cache_hits"] == 3


async def test_undecodable_url_is_cached_but_a_transport_failure_is_not():
    """A timeout says nothing about the image; caching it would be permanent."""
    hasher, fetcher = _hasher(
        {
            "https://img/video.webm": b"\x1aE\xdf\xa3 not an image",
            "https://img/flaky.png": TimeoutError("connect timeout"),
        }
    )
    for _ in range(3):
        await hasher.hash_url("https://img/video.webm")
        await hasher.hash_url("https://img/flaky.png")

    assert fetcher.calls.count("https://img/video.webm") == 1
    assert fetcher.calls.count("https://img/flaky.png") == 3
    assert hasher.stats["failed"] == 3


async def test_sweep_image_budget_is_enforced():
    alpha = (FIXTURES / "alpha.png").read_bytes()
    responses = {f"https://img/{i}.png": alpha for i in range(10)}
    hasher, fetcher = _hasher(responses, max_images_per_sweep=3)
    posts = [_post(url) for url in responses]

    added = await hasher.hash_posts(posts)
    assert added == 3
    assert len(fetcher.calls) == 3
    assert hasher.stats["skipped_budget"] == 7


async def test_the_sweep_budget_is_spent_across_posts_not_per_post():
    """Each post must draw down the same pool, or the cap is per-post in disguise."""
    alpha = (FIXTURES / "alpha.png").read_bytes()
    responses = {f"https://img/{i}.png": alpha for i in range(8)}
    hasher, fetcher = _hasher(responses, max_images_per_sweep=3, max_images_per_post=1)
    await hasher.hash_posts([_post(url) for url in responses])
    assert len(fetcher.calls) == 3


async def test_deadline_stops_hashing_even_with_budget_left():
    alpha = (FIXTURES / "alpha.png").read_bytes()
    responses = {f"https://img/{i}.png": alpha for i in range(5)}
    hasher, fetcher = _hasher(responses, deadline_seconds=0.0)
    assert await hasher.hash_posts([_post(url) for url in responses]) == 0
    assert fetcher.calls == []


async def test_deadline_is_checked_between_images_not_only_between_posts():
    """One post with several slow images must not run past the window alone."""
    alpha = (FIXTURES / "alpha.png").read_bytes()
    responses = {f"https://img/{i}.png": alpha for i in range(4)}
    hasher, fetcher = _hasher(responses, deadline_seconds=0.01)

    slow = fetcher

    async def slow_fetch(url: str) -> bytes:
        await asyncio.sleep(0.05)
        return await _Fetcher.__call__(slow, url)

    hasher._fetcher = slow_fetch
    await hasher.hash_posts([_post(*responses)])
    assert len(fetcher.calls) == 1, "the deadline expired after the first image"


async def test_per_post_image_cap_is_enforced():
    alpha = (FIXTURES / "alpha.png").read_bytes()
    responses = {f"https://img/{i}.png": alpha for i in range(6)}
    hasher, fetcher = _hasher(responses, max_images_per_post=2)

    await hasher.hash_posts([_post(*responses)])
    assert len(fetcher.calls) == 2


async def test_posts_already_carrying_a_perceptual_hash_are_skipped():
    hasher, fetcher = _hasher({"https://img/a.png": (FIXTURES / "alpha.png").read_bytes()})
    post = _post("https://img/a.png", hashes=[perceptual_label("0" * 16)])

    assert await hasher.hash_posts([post]) == 0
    assert fetcher.calls == []


async def test_an_exact_hash_does_not_block_perceptual_hashing():
    """4chan gives us an MD5; that is not the hash the remix metric can use."""
    hasher, _ = _hasher({"https://img/a.png": (FIXTURES / "alpha.png").read_bytes()})
    post = _post("https://img/a.png", hashes=[exact_label("deadbeef")])

    assert await hasher.hash_posts([post]) == 1
    assert len(perceptual_values(post.media_hashes)) == 1


async def test_disabled_hasher_does_nothing():
    hasher, fetcher = _hasher({"https://img/a.png": b""}, enabled=False)
    assert await hasher.hash_posts([_post("https://img/a.png")]) == 0
    assert fetcher.calls == []


class _Body:
    def __init__(self, chunks: list[bytes]) -> None:
        self.chunks = chunks
        self.status_code = 200
        self.delivered = 0

    async def aiter_bytes(self):
        for chunk in self.chunks:
            self.delivered += len(chunk)
            yield chunk


async def test_byte_cap_stops_the_transfer_rather_than_truncating():
    """Truncated JPEG bytes can still decode, into a picture nobody posted."""
    hasher, _ = _hasher({}, max_bytes=1000)
    body = _Body([b"x" * 400] * 10)

    with pytest.raises(Exception, match="exceeds 1000 bytes"):
        await hasher._read_capped(body)
    # Stopped as soon as the cap was crossed, not after draining the response.
    assert body.delivered == 1200


async def test_empty_body_is_a_failure_not_an_absence():
    hasher, _ = _hasher({}, max_bytes=1000)
    with pytest.raises(Exception, match="empty body"):
        await hasher._read_capped(_Body([]))


async def test_pipeline_hashes_posts_before_they_are_written(tmp_path):
    """The store has no key to come back with, so this is the only chance.

    `insert_posts` is the single path into the store, and a post row is keyed by
    (platform, post_id) with no route back from a URL — hashing after the write
    would mean the hashes never land.
    """
    from botsensai.collectors.base import CollectionResult
    from botsensai.config import load_settings
    from botsensai.pipeline import Pipeline
    from botsensai.store.db import Database
    from botsensai.util.synthetic import generate_token

    settings = load_settings()
    settings.db_path = str(tmp_path / "media.db")
    pipeline = Pipeline(settings, db=Database(settings.db_path), collectors=[])
    launch = generate_token("organic", seed=3).launch

    post = _post("https://img/a.png")
    post.token_key = launch.token.key
    harvested = CollectionResult(
        surface="x",
        started_at=datetime.fromisoformat("2026-08-01T00:00:00+00:00"),
        finished_at=datetime.fromisoformat("2026-08-01T00:00:01+00:00"),
        posts=[post],
    )

    async def fake_sweep(tokens):
        return [harvested]

    order: list[str] = []

    async def fake_hash(posts):
        order.append("hash")
        for p in posts:
            p.media_hashes.append(perceptual_label("dead" * 4))
        return len(posts)

    original_insert = pipeline.db.insert_posts

    def spy_insert(posts):
        order.append("insert")
        # The point of the ordering: the row that reaches the store carries it.
        assert all(perceptual_values(p.media_hashes) for p in posts)
        return original_insert(posts)

    pipeline.collectors.sweep_enrich = fake_sweep
    pipeline.media_hasher.hash_posts = fake_hash
    pipeline.db.insert_posts = spy_insert

    await pipeline.enrich([launch])
    assert order == ["hash", "insert"]


@pytest.mark.parametrize(
    ("url", "expected"),
    [
        (
            "https://pbs.twimg.com/media/ABC123.jpg",
            "https://pbs.twimg.com/media/ABC123?format=jpg&name=small",
        ),
        (
            "https://pbs.twimg.com/media/ABC123.jpg?name=orig",
            "https://pbs.twimg.com/media/ABC123?format=jpg&name=small",
        ),
        ("https://i.4cdn.org/biz/1690000000000.png", "https://i.4cdn.org/biz/1690000000000s.jpg"),
        ("https://i.4cdn.org/biz/1690000000000.webm", "https://i.4cdn.org/biz/1690000000000.webm"),
        ("https://example.invalid/pic.png", "https://example.invalid/pic.png"),
    ],
)
def test_thumbnail_rewriting(url, expected):
    assert thumbnail_url(url) == expected
