"""Wash-trading and fake contention detection via wallet dispersion and Gini coefficient."""

from __future__ import annotations

from botsensai.config import Settings, get_settings
from botsensai.models import Trade, VetoReason
from botsensai.util.logging import get_logger

log = get_logger(__name__)


def calculate_gini(values: list[float]) -> float:
    """Calculate Gini coefficient of inequality for an array of values."""
    if not values or len(values) < 2:
        return 0.0
    sorted_vals = sorted(values)
    n = len(values)
    total = sum(sorted_vals)
    if total <= 0:
        return 0.0
    index = sum((2 * i - n - 1) * val for i, val in enumerate(sorted_vals, 1))
    return float(index / (n * total))


class WashTradeFilter:
    """Detects artificial volume generated by circular self-trading."""

    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()

    def evaluate_trades(self, trades: list[Trade]) -> VetoReason | None:
        """Check if trading flow exhibits circular wash trading characteristics."""
        if not self.settings.scoring.veto_wash_trading or len(trades) < 6:
            return None

        wallet_counts: dict[str, int] = {}
        wallet_volumes: dict[str, float] = {}

        for t in trades:
            if t.wallet:
                wallet_counts[t.wallet] = wallet_counts.get(t.wallet, 0) + 1
                wallet_volumes[t.wallet] = wallet_volumes.get(t.wallet, 0.0) + (t.amount_native or 0.0)

        # High wallet concentration: < 3 wallets generating > 75% of trades
        total_trades = len(trades)
        top_wallets_trades = sum(sorted(wallet_counts.values(), reverse=True)[:2])
        if (top_wallets_trades / total_trades) >= 0.75:
            log.warning(
                "wash_trading.high_concentration",
                top_wallets_share=top_wallets_trades / total_trades,
                trades=total_trades,
            )
            return VetoReason.WASH_TRADING_DETECTED

        # Calculate Gini coefficient of transaction sizes
        gini = calculate_gini(list(wallet_volumes.values()))
        if gini >= 0.90 and len(wallet_counts) > 3:
            log.warning("wash_trading.extreme_gini_inequality", gini=gini)
            return VetoReason.WASH_TRADING_DETECTED

        return None
